# Generated by Django 4.0.4 on 2022-05-15 12:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_appointment_remove_category_subscribers_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Appointment',
        ),
    ]
